package de.zeiss.mongodb_ws.spring_geo_service.rest.controller;

import de.zeiss.mongodb_ws.spring_geo_service.rest.model.PointOfInterest;
import de.zeiss.mongodb_ws.spring_geo_service.service.PointOfInterestService;
import org.geojson.Point;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.logging.Logger;

@RestController
@RequestMapping(value = "/api/poi")
public class PointOfInterestController {

    @Autowired
    private PointOfInterestService poiService;

    private List<PointOfInterest> mockPOIs = new ArrayList<>();

    private static final Logger logger = Logger.getLogger(PointOfInterestController.class.getName());

    @GetMapping(value = "/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public PointOfInterest getPointOfInterest(@PathVariable("id") String id) {
        logger.info("Received request for POI with id: " + id);
        PointOfInterest poi = poiService.getPointOfInterestById(id);

        if (poi == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Point of Interest with id " + id + " not found.");
        }

        poi.setHref(ServletUriComponentsBuilder.fromCurrentRequestUri().toUriString());
        return poi;
    }

    @GetMapping
    public Collection<PointOfInterest> findPointsOfInterest(@RequestParam double lat, @RequestParam double lon,
                                                            @RequestParam int radius, @RequestParam(value = "expand", required = false) String expand) {

        List<PointOfInterest> poiList = poiService.listPOIs(lat, lon, radius, "details".equalsIgnoreCase(expand));

        for (PointOfInterest poi : poiList) {
            String href = ServletUriComponentsBuilder.fromCurrentRequest()
                    .path("/{id}")
                    .buildAndExpand(poi.getId()).toUriString();

            poi.setHref(href);
        }

        return poiList;
    }

    @PostMapping
    public ResponseEntity<Void> create(@RequestBody PointOfInterest resource) {
        ensureMockPOIsInitialized();
        PointOfInterest mockPOI = createMockPOI("new-poi");
        mockPOI.setCategory(resource.getCategory());
        mockPOI.setName(resource.getName());
        mockPOI.setDetails(resource.getDetails());
        mockPOI.setLocation(resource.getLocation());
        mockPOIs.add(mockPOI);
        // set the Location header
        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(mockPOI.getId())
                .toUri();

        logger.info("Location header for created POI: " + location);
        return ResponseEntity.created(location).build();
    }

    @PutMapping(value = "/{id}")
    @ResponseStatus(HttpStatus.OK)
    public void update(@PathVariable("id") Long id, @RequestBody PointOfInterest resource) {
        // TODO implement update logic
    }

    @DeleteMapping(value = "/{id}")
    @ResponseStatus(HttpStatus.OK)
    public void delete(@PathVariable("id") Long id) {
        // TODO implement delete logic
    }

    private void ensureMockPOIsInitialized() {
        if (mockPOIs.isEmpty()) {
            mockPOIs.add(createMockPOI("poi1"));
            mockPOIs.add(createMockPOI("poi2"));
            mockPOIs.add(createMockPOI("poi3"));
        }
    }

    private PointOfInterest createMockPOI(String id) {
        PointOfInterest poi = new PointOfInterest();
        poi.setId(id);
        // set href using the ServletUriComponentsBuilder
        String uriString = ServletUriComponentsBuilder.fromCurrentRequestUri().toUriString();

        if (!uriString.endsWith("/" + id)) {
            uriString = uriString + "/" + id;
        }

        poi.setHref(uriString);
        poi.setCategory("coffee");
        poi.setName("Mock POI " + id);
        poi.setDetails("A mock poi generated by the Spring Boot backend.");

        poi.setLocation(new Point(getRandomCoordinateValueBetween(13.7, 13.8), getRandomCoordinateValueBetween(51.0, 51.1)));
        return poi;
    }

    private double getRandomCoordinateValueBetween(double min, double max) {
        return min + (Math.random() * (max - min));
    }
}
